import { FC } from "react";
import { SignMessage } from "../../components/SignMessage";
import { SendTransaction } from "../../components/SendTransaction";

export const BasicsView: FC = ({}) => {
  return (
    <div className="md:hero mx-auto p-4">
      <div className="md:hero-content flex flex-col">
        <h1 className="text-center text-5xl font-bold text-transparent bg-clip-text bg-gradient-to-tr from-[#4f9ff5] to-[#ffffff]">
          Roadmap
        </h1>
        {/* CONTENT GOES HERE */}
        <div className="text-center px-20">
          {/* <SignMessage/> */}
          {/* <SendTransaction /> */}
          <div className="py-2">
            <h1 className="text-2xl pb-2">Phase 1:</h1>
            <h3>Complete our Auction Site for our Legendary 1 of 1 Bonkers.</h3>
            Our first project already in development and currently 70% finished
            is an in-house auction app using Bonk! We are going to collaborate
            with pixel artists within the SOL Community to create Legendary
            Bonker 1 of 1's that the community can bid on with Bonk! The funds
            from auction sales will be split between the dao and the artist who
            collaborates.
          </div>{" "}
          <div className="py-2">
            <h2 className="text-2xl pb-2">Phase 2:</h2>
            <h3>
              Get the developer community involved and roll out Revenue Share!
            </h3>
            Wouldn't you like to reap what you sow? Our aim is to get as many
            devs in the Solana community involved by issuing bounties that can
            generate revenue our holders can share! All revenue generated by
            community projects will be split with 65% going to holders and 35%
            split between the team and DAO.
          </div>
          <div className="py-2">
            <h2 className="text-2xl pb-2">Phase 3:</h2>
            <h3>
              Continue to build cool things within our community, learn, and
              have fun throughout the bear market.
            </h3>
            Let's make the best of this bear market by sticking together,
            learning how to build awesome projects that can benefit us, and
            having a great time doing it!
          </div>
          <h2 className="text-center py-3 text-5xl font-bold text-transparent bg-clip-text bg-gradient-to-tr from-[#4f9ff5] to-[#ffffff]">
            Fund Allocation
          </h2>
          <div className="text-center">
            <ul className="py-2">
              <li className="py-2">
                <strong className="text-xl">50%</strong> of funds will be
                allocated to further develop fun utilities for Solana and Bonk!
              </li>
              <li className="py-2">
                {" "}
                <strong className="text-xl">30%</strong> of funds will be to pay
                the devs/holders in our community to continue to build and
                implement Bonk in fun ways! Not only will the in-house devs
                continue to build but we also have planned out SOL/Bonk!
                bounties for the community to get involved!{" "}
              </li>
              <li className="py-2">
                {" "}
                <strong className="text-xl">10%</strong> of funds will go to our
                artist!
              </li>
              <li className="py-2">
                {" "}
                <strong className="text-xl">10%</strong> of the remaining funds
                will be held in our treasury for miscellaneous things such as
                contest and giveaways!
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};
